---
# Product
- name: 'find product'
  shell: >
    {{ katello_provisioning_hammer }} product info
    --name "CentOS"
    --organization "{{ katello_provisioning_organization }}"
  register: katello_provisioning_product
  ignore_errors: True

- name: 'create centos product'
  shell: >
    {{ katello_provisioning_hammer }} product create
    --name "CentOS"
    --organization "{{ katello_provisioning_organization }}"
  when: katello_provisioning_product.stderr.find('not found') != -1

# CentOS
- name: 'find centos repo'
  shell: >
    {{ katello_provisioning_hammer }} repository info
    --name "CentOS 7"
    --product "CentOS"
    --organization "{{ katello_provisioning_organization }}"
  register: katello_provisioning_repo
  ignore_errors: True

- name: 'create centos repo'
  shell: >
    {{ katello_provisioning_hammer }} repository create
    --product="CentOS"
    --content-type="yum"
    --name "CentOS 7"
    --url http://mirror.centos.org/centos/7/os/x86_64
    --download-policy {{ katello_provisioning_download_policy }}
    --organization "{{ katello_provisioning_organization }}"
  when: katello_provisioning_repo.stderr.find('not found') != -1

- name: 'sync the centos repo'
  shell: >
    {{ katello_provisioning_hammer }} repository synchronize
    --name "CentOS 7"
    --product "CentOS"
    --organization "{{ katello_provisioning_organization }}"
  when: katello_provisioning_sync_repos

# Katello Agent
- name: 'find agent repo'
  shell: >
    {{ katello_provisioning_hammer }} repository info
    --name "Katello Agent"
    --product "CentOS"
    --organization "{{ katello_provisioning_organization }}"
  register: katello_provisioning_repo
  ignore_errors: True

- name: 'create agent repo'
  shell: >
    {{ katello_provisioning_hammer }} repository create
    --product="CentOS"
    --content-type="yum"
    --name "Katello Agent"
    --url https://fedorapeople.org/groups/katello/releases/yum/nightly/client/el7/x86_64/
    --download-policy {{ katello_provisioning_download_policy }}
    --organization "{{ katello_provisioning_organization }}"
  when: katello_provisioning_repo.stderr.find('not found') != -1

- name: 'sync the agent repo'
  shell: >
    {{ katello_provisioning_hammer }} repository synchronize
    --name "Katello Agent"
    --product "CentOS"
    --organization "{{ katello_provisioning_organization }}"
  when: katello_provisioning_sync_repos

# Puppet 4
- name: 'find puppet4 repo'
  shell: >
    {{ katello_provisioning_hammer }} repository info
    --name "Puppet 4"
    --product "CentOS"
    --organization "{{ katello_provisioning_organization }}"
  register: katello_provisioning_repo
  ignore_errors: True

- name: 'create puppet4 repo'
  shell: >
    {{ katello_provisioning_hammer }} repository create
    --product="CentOS"
    --content-type="yum"
    --name "Puppet 4"
    --url http://yum.puppetlabs.com/el/7/PC1/x86_64
    --download-policy {{ katello_provisioning_download_policy }}
    --organization "{{ katello_provisioning_organization }}"
  when: katello_provisioning_repo.stderr.find('not found') != -1

- name: 'sync the puppet4 repo'
  shell: >
    {{ katello_provisioning_hammer }} repository synchronize
    --name "Puppet 4"
    --product "CentOS"
    --organization "{{ katello_provisioning_organization }}"
  when: katello_provisioning_sync_repos

# Activation key
- name: 'find activation key'
  shell: >
    {{ katello_provisioning_hammer }} activation-key info
    --name "CentOS 7"
    --organization "{{ katello_provisioning_organization }}"
  register: katello_provisioning_activation_key
  ignore_errors: True

- name: 'create activation key'
  shell: >
    {{ katello_provisioning_hammer }} activation-key create
    --organization "{{ katello_provisioning_organization }}"
    --name="CentOS 7"
    --content-view="Default Organization View"
    --lifecycle-environment="Library"
    --unlimited-hosts
  when: katello_provisioning_activation_key.stderr.find('not found') != -1

# Host group
- name: 'find hostgroup Forklift Katello CentOS 7'
  shell: >
    {{ foreman_provisioning_hammer }} hostgroup info --name 'Forklift Katello CentOS 7'
  register: katello_provisioning_hostgroup_katello_centos
  ignore_errors: True

- name: 'create Forklift Katello CentOS 7 host group'
  shell: >
    {{ katello_provisioning_hammer }} hostgroup create
    --name "Forklift Katello CentOS 7"
    --content-view "Default Organization View"
    --lifecycle-environment Library
    --query-organization "{{ katello_provisioning_organization }}"
    --content-source-id {{ foreman_provisioning_smart_proxy.Id }}
    --kickstart-repository-id 1
    --operatingsystem "CentOS_Linux 7"
    --medium 'CentOS mirror'
    --partition-table 'Kickstart default'
    --parent 'Forklift Base'
    {{ foreman_provisioning_hammer_taxonomy_params }}
  when: katello_provisioning_hostgroup_katello_centos.stderr.find('not found') != -1


- name: 'set enable-puppet4 parameter'
  shell: >
      {{ katello_provisioning_hammer }} hostgroup set-parameter
      --hostgroup "Forklift CentOS 7"
      --name enable-puppet4
      --value true

# Lifecycle environments
- name: 'find lifecycle-environment Development'
  shell: >
    {{ katello_provisioning_hammer }} lifecycle-environment info
    --name Development
    --organization "{{ katello_provisioning_organization }}"
  register: katello_provisioning_lce_development
  ignore_errors: True

- name: 'create lifecycle-environment Development'
  shell: >
    {{ katello_provisioning_hammer }} lifecycle-environment create
    --name Development --prior Library
    --organization "{{ katello_provisioning_organization }}"
  when: katello_provisioning_lce_development.stderr.find('not found') != -1

- name: 'find lifecycle-environment Production'
  shell: >
    {{ katello_provisioning_hammer }} lifecycle-environment info
    --name Development
    --organization "{{ katello_provisioning_organization }}"
  register: katello_provisioning_lce_production
  ignore_errors: True

- name: 'create lifecycle-environment Production'
  shell: >
    {{ katello_provisioning_hammer }} lifecycle-environment create
    --name Production --prior Development
    --organization "{{ katello_provisioning_organization }}"
  when: katello_provisioning_lce_production.stderr.find('not found') != -1
