---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pulp-celerybeat
  namespace: "{{ project_name }}"
  labels:
    app: pulp-celerybeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulp-celerybeat
  template:
    metadata:
      labels:
        app: pulp-celerybeat
    spec:
      containers:
        - name: pulp-celerybeat
          securityContext: {}
          image: "{{ registry }}/pulp-celerybeat:latest"
      serviceAccount: anyuid
      serviceAccountName: anyuid
