---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pulp-streamer
  namespace: "{{ project_name }}"
  labels:
    app: pulp-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulp-streamer
  template:
    metadata:
      labels:
        app: pulp-streamer
    spec:
      containers:
        - name: pulp-streamer
          securityContext: {}
          ports:
            - protocol: TCP
              containerPort: 8751
          image: "{{ registry }}/pulp-streamer:latest"
      serviceAccount: anyuid
      serviceAccountName: anyuid
