---
- hosts: localhost
  vars:
    resource_path: ../..
  vars_files:
    - parameters.yml
  tasks:
    - name: 'Create .tmp directory'
      file:
        path: "{{ resource_path }}/.tmp"

    - name: 'Clone templates repository'
      git:
        repo: https://github.com/openshift/openshift-ansible.git
        dest: "{{ resource_path }}/.tmp/openshift-ansible"

    - name: 'Create Foreman project'
      command: oc new-project foreman-katello --description="Foreman with Katello on Openshift" --display-name="The Foreman with Katello"

    - name: 'Load default imagestreams'
      command: oc create -f {{ resource_path }}/.tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/image-streams/image-streams-centos7.json

    - name: 'Load quickstart templates'
      command: oc create -f {{ resource_path }}/.tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/quickstart-templates

    - name: 'Create Persistent Volume Claim'
      command: oc create -f {{ resource_path }}/claims/local-data.yaml

    - name: 'Create Postgresql template'
      command: oc create -f {{ resource_path }}/templates/postgresql.yaml

    - name: 'Create MongoDB template'
      command: oc create -f {{ resource_path }}/templates/mongodb.yaml
    
    - name: 'Create Candlepin template'
      command: oc create -f {{ resource_path }}/templates/candlepin.yaml
    
    - name: 'Create Puppetserver template'
      command: oc create -f {{ resource_path }}/templates/puppet.yaml
    
    - name: 'Create Foreman Proxy template'
      command: oc create -f {{ resource_path }}/templates/foreman-proxy.yaml
    
    - name: 'Create Foreman template'
      command: oc create -f {{ resource_path }}/templates/foreman.yaml
    
    - name: 'Create Pulp template'
      command: oc create -f {{ resource_path }}/templates/pulp.yaml
    
    - name: 'Create Qpid template'
      command: oc create -f {{ resource_path }}/templates/qpid.yaml

    - name: 'Create Postgres application'
      shell: >
        oc process postgresql
        POSTGRESQL_USER={{ postgresql_user }}
        POSTGRESQL_PASSWORD={{ postgresql_password }}
        POSTGRESQL_DATABASE={{ postgresql_database }}
        | oc create -f -

    - name: 'Create MongoDB application'
      shell: >
        oc process mongodb
        MONGODB_USER={{ mongodb_user }}
        MONGODB_ADMIN_PASSWORD={{ mongodb_password }}
        MONGODB_PASSWORD={{ mongodb_password }}
        MONGODB_DATABASE={{ mongodb_database }}
        | oc create -f -

    - name: 'Create Candlepin application'
      shell: >
        oc process candlepin
        DATABASE_USER={{ postgresql_user }}
        DATABASE_PASSWORD={{ postgresql_password }}
        DATABASE_NAME={{ postgresql_database }}
        | oc create -f -

    - name: 'Create Qpid application'
      shell: oc process qpid | oc create -f -

    - name: 'Create Pulp application'
      shell: >
        oc process pulp
        DATABASE_USER={{ mongodb_user }}
        DATABASE_PASSWORD={{ mongodb_password }}
        DATABASE_NAME={{ mongodb_database }}
        | oc create -f -

    - name: 'Create Foreman application'
      shell: >
        oc process foreman
        ENABLE_KATELLO={{ enable_katello }}
        DATABASE_USER={{ postgresql_user }}
        DATABASE_NAME={{ postgresql_database }}
        DATABASE_PASSWORD={{ postgresql_password }}
        | oc create -f -

    - name: 'Create Foreman Proxy application'
      shell: oc process foreman-proxy | oc create -f -

    - name: 'Create Puppetserver application'
      shell: oc process puppet | oc create -f -
