---
postgresql_user: "foreman"
postgresql_password: "foreman"
postgresql_database: "foreman"
postgresql_port: "5432"
postgresql_host: "postgresql"

mongodb_user: "admin"
mongodb_password: "admin"
mongodb_database: "pulp_database"

enable_katello: "true"
