---
- hosts: localhost
  vars:
    resource_path: ../../
  vars_files:
    - parameters.yml
  tasks:
    - name: 'Update Persistent Volume Claim'
      command: oc replace -f {{ resource_path }}claims/pulp_content.yaml

    - name: 'Update Candlepin template'
      command: oc replace -f {{ resource_path }}templates/candlepin.yaml
    
    - name: 'Update Qpid template'
      command: oc replace -f {{ resource_path }}templates/qpid.yaml
    
    - name: 'Update Pulp template'
      command: oc replace -f {{ resource_path }}templates/pulp.yaml
    
    - name: 'Update Puppetserver template'
      command: oc replace -f {{ resource_path }}templates/puppet.yaml
    
    - name: 'Update Foreman template'
      command: oc replace -f {{ resource_path }}templates/foreman.yaml
    
    - name: 'Update Foreman Proxy template'
      command: oc replace -f {{ resource_path }}templates/foreman-proxy.yaml

    - name: 'Update Postgres application'
      shell: >
        oc process postgresql-ephemeral
        POSTGRESQL_USER={{ postgresql_user }}
        POSTGRESQL_PASSWORD={{ postgresql_password }}
        POSTGRESQL_DATABASE={{ postgresql_database }}
        | oc replace -f -
      ignore_errors: true

    - name: 'Update MongoDB application'
      shell: >
        oc process mongodb-ephemeral
        MONGODB_USER={{ mongodb_user }}
        MONGODB_ADMIN_PASSWORD={{ mongodb_password }}
        MONGODB_PASSWORD={{ mongodb_password }}
        MONGODB_DATABASE={{ mongodb_database }}
        | oc replace -f -
      ignore_errors: true

    - name: 'Update Candlepin application'
      command: >
        oc process candlepin
        DATABASE_USER={{ postgresql_user }}
        DATABASE_PASSWORD={{ postgresql_password }}
        DATABASE_NAME={{ postgresql_database }}
        | oc replace -f -
      ignore_errors: true

    - name: 'Update Qpid application'
      shell: oc process qpid | oc replace -f -
      ignore_errors: true

    - name: 'Update Pulp application'
      shell: >
        oc process pulp
        DATABASE_USER={{ mongodb_user }}
        DATABASE_PASSWORD={{ mongodb_password }}
        DATABASE_NAME={{ mongodb_database }}
        | oc replace -f -
      ignore_errors: true

    - name: 'Update Foreman application'
      shell: >
        oc process foreman
        ENABLE_KATELLO={{ enable_katello }}
        DATABASE_USER={{ postgresql_user }}
        DATABASE_NAME={{ postgresql_database }}
        DATABASE_PASSWORD={{ postgresql_password }}
        | oc replace -f -
      ignore_errors: true

    - name: 'Update Foreman Proxy application'
      shell: oc process foreman-proxy | oc replace -f -
      ignore_errors: true

    - name: 'Update Puppetserver application'
      shell: oc process puppet | oc replace -f -
      ignore_errors: true
