---
- hosts: localhost
  vars:
    resource_path: ../../
  vars_files:
    - parameters.yml
  tasks:
    - name: 'Update Persistent Volume Claim'
      command: oc replace -f {{ resource_path }}claims/pulp_content.yaml

    - name: 'Update Candlepin template'
      command: oc replace -f {{ resource_path }}templates/candlepin.yaml
    
    - name: 'Update Qpid template'
      command: oc replace -f {{ resource_path }}templates/qpid.yaml
    
    - name: 'Update Pulp template'
      command: oc replace -f {{ resource_path }}templates/pulp.yaml
    
    - name: 'Update Puppetserver template'
      command: oc replace -f {{ resource_path }}templates/puppet.yaml
    
    - name: 'Update Foreman template'
      command: oc replace -f {{ resource_path }}templates/foreman.yaml
    
    - name: 'Update Foreman Proxy template'
      command: oc replace -f {{ resource_path }}templates/foreman-proxy.yaml

    - name: 'Update Postgres application'
      command: >
        oc new-app postgresql-ephemeral
        -p POSTGRESQL_USER={{ postgresql_user }}
        -p POSTGRESQL_PASSWORD={{ postgresql_password }}
        -p POSTGRESQL_DATABASE={{ postgresql_database }}
      ignore_errors: true

    - name: 'Update MongoDB application'
      command: >
        oc new-app mongodb-ephemeral
        -p MONGODB_USER={{ mongodb_user }}
        -p MONGODB_ADMIN_PASSWORD={{ mongodb_password }}
        -p MONGODB_PASSWORD={{ mongodb_password }}
        -p MONGODB_DATABASE={{ mongodb_database }}
      ignore_errors: true

    - name: 'Update Candlepin application'
      command: >
        oc new-app candlepin
        -p DATABASE_USER={{ postgresql_user }}
        -p DATABASE_PASSWORD={{ postgresql_password }}
        -p DATABASE_NAME={{ postgresql_database }}
      ignore_errors: true

    - name: 'Update Qpid application'
      command: oc new-app qpid
      ignore_errors: true

    - name: 'Update Pulp application'
      command: >
        oc new-app pulp
        -p DATABASE_USER={{ mongodb_user }}
        -p DATABASE_PASSWORD={{ mongodb_password }}
        -p DATABASE_NAME={{ mongodb_database }}
      ignore_errors: true

    - name: 'Update Foreman application'
      command: >
        oc new-app foreman
        -p ENABLE_KATELLO={{ enable_katello }}
        -p DATABASE_USER={{ postgresql_user }}
        -p DATABASE_NAME={{ postgresql_database }}
        -p DATABASE_PASSWORD={{ postgresql_password }}
      ignore_errors: true

    - name: 'Update Foreman Proxy application'
      command: oc new-app foreman-proxy
      ignore_errors: true

    - name: 'Update Puppetserver application'
      command: oc new-app puppet
      ignore_errors: true
