---
dependencies:
  - role: selinux
  - role: etc_hosts
  - role: epel_repositories
  - role: ostree_repositories
  - role: puppet_repositories
  - role: foreman_repositories
  - role: katello_repositories
  - role: foreman_installer
    foreman_installer_scenario: katello
    foreman_installer_options:
      - "{{ '--disable-system-checks' if katello_repositories_version != '3.1' else '' }}"
    foreman_installer_scenarios_answers:
      foreman:
        admin_password: changeme
    foreman_installer_pkg: katello
