katello:
  installer: 'foreman-installer --scenario katello'
  packages:
    - katello

katello-devel:
  installer: 'foreman-installer --scenario katello-devel'
  packages:
    - foreman-installer-katello-devel

foreman:
  installer: 'foreman-installer --scenario foreman'
  packages:
    - foreman-installer
