sudo: false
language: python
python:
  - 2.7
before_install:
  - cd vagrant
install:
  - pip install ansible-lint
  - rvm install 2.2.4
script:
  - bundle install
  - bundle exec rake
  - ansible-lint -r rules/ playbooks/*
