language: ruby
rvm:
  - "2.0.0"
dist: bionic
script:
  - |
    if git diff origin/master --name-only | grep -q "vagrant"; then
      cd vagrant
      bundle install --jobs=3 --retry=3
      bundle exec rake
    fi
