---
- hosts: localhost
  tasks:
    - name: 'Create .tmp directory'
      file:
        path: .tmp

    - name: 'Clone templates repository'
      git:
        repo: https://github.com/openshift/openshift-ansible.git
        dest: .tmp/openshift-ansible

    - name: 'Create Qpid project'
      command: oc new-project qpid --description="Qpid on Openshift" --display-name="Qpid"

    - name: 'Load default imagestreams'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/image-streams/image-streams-centos7.json

    - name: 'Load database templates'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/db-templates

    - name: 'Load quickstart templates'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/quickstart-templates
    
    - name: 'Create Qpid template'
      command: oc create -f templates/qpid.yaml

    - name: 'Create Qpid application'
      command: >
        oc new-app qpid
