---
- name: Enable ruby:2.7 module
  dnf:
    name: '@ruby:2.7'
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '8'
    - foreman_repositories_version is defined
    - foreman_repositories_version == "nightly" or foreman_repositories_version is version ('2.5', '>=')

- name: 'Install foreman-installer'
  package:
    name: foreman-installer
    state: latest
  tags:
    - packages

- name: 'Install additional packages'
  package:
    name: "{{ foreman_installer_additional_packages }}"
    state: latest
  tags:
    - packages
