---
- name: 'Stop services'
  command: foreman-maintain service stop

- name: 'Update packages'
  import_role:
    name: update_os_packages

- set_fact:
    foreman_installer_options_internal_use_only: "{{ [ '--upgrade', '--certs-update-all' ] + foreman_installer_options_internal_use_only }}"
  when: foreman_installer_version_file['content'] | b64decode is version('2.1', '<')

- name: 'Run installer upgrade'
  import_tasks: "install.yml"
  vars:
    foreman_installer_disable_system_checks: true
