---
- name: 'Stop services'
  command: foreman-maintain service stop

- name: 'Update packages'
  import_role:
    name: update_os_packages

- name: 'Set foreman installer options for upgrade'
  set_fact:
    foreman_installer_options_internal_use_only: "{{ [ '--upgrade', '--certs-update-all' ] + foreman_installer_options_internal_use_only }}"
  when: foreman_installer_version is version('2.1', '<')

- name: 'Set foreman installer options for upgrade'
  set_fact:
    foreman_installer_options_internal_use_only: "{{ foreman_installer_options_internal_use_only.remove('--upgrade') }}"
  when: foreman_installer_version is version('2.1', '>=') and '--upgrade' in foreman_installer_options_internal_use_only

- name: 'Run installer upgrade'
  import_tasks: "install.yml"
  vars:
    foreman_installer_disable_system_checks: true
    foreman_installer_options_internal_use_only: "{{ foreman_installer_options_internal_use_only }}"
