---
name: upgrade_32_to_33
description: "Installs Katello and Proxy 3.1 and then upgrades to 3.3"
boxes:
  pipeline-katello-3.2-3.3-centos7:
    box: centos7
    memory: 4680
  pipeline-proxy-3.2-3.3-centos7:
    box: centos7
    memory: 3072
playbooks:
  - install_katello_32.yml
  - install_proxy_32.yml
  - bats_on_katello.yml
  - bats_on_proxy.yml
  - upgrade_katello.yml
