---
- include_tasks: "{{ foreman_client_repositories_environment }}_repo.yml"
  when:
    - ansible_os_family == 'RedHat'

- name: 'Clean yum'
  command: 'yum clean all'
  args:
    warn: false
  tags:
    - packages
  when: ansible_os_family == 'RedHat'
