---
- name: "Set up {{ katello_repositories_environment }} repositories"
  include_tasks: "{{ katello_repositories_environment }}_repos.yml"

- name: enable powertools for libdb_cxx used by qpid-cpp-server-linearstore
  command: dnf config-manager --set-enabled powertools
  when: ansible_distribution_major_version == "8"
