---
- name: 'Setup Katello {{ katello_repositories_version }} Repository'
  yum:
    name: https://{{ 'yum.theforeman.org/katello' if (katello_repositories_version == 'nightly' or katello_repositories_version is version('4.1', '>=')) else 'fedorapeople.org/groups/katello/releases/yum' }}/{{ katello_repositories_version }}/katello/el{{ ansible_distribution_major_version }}/x86_64/katello-repos-latest.rpm
    disable_gpg_check: True
    state: present
