- name: Manage the lifecycle of Foreman on OpenShift™
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    minishift: true
    minikube: false
    openshift: "{{ minishift }}"
    kubernetes: "{{ minikube }}"
    cluster_up: false
    pulpworkercount: 3
    registry: quay.io/foreman
    deployment_state: present
  pre_tasks:
    - name: 'Set openshift false if minikube'
      set_fact:
        minishift: false
        openshift: false
      when: minikube

    - name: 'Set kubernetes false if minishift'
      set_fact:
        minikube: false
        kubernetes: false
      when: minishift

    - name: 'Set project name'
      set_fact:
        project_name: "{{ project_name | default('foreman') }}"

    - set_fact:
        application_hostname: "{{ application_hostname | default('') }}"
    - shell: minishift ip
      register: minishift_ip
      when: minishift == true
    - set_fact:
        application_hostname: "foreman.{{ minishift_ip.stdout }}.nip.io"
      when: application_hostname == '' and minishift == true and cluster_up == false
    - set_fact:
        application_hostname: "foreman.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.nip.io"
      when: application_hostname == '' and cluster_up == true and minishift == false

    - name: Login as developer
      command: oc login -u developer -p a
      when: minishift or cluster_up
  roles:
    - project
    - service-accounts
    - pulp
    - foreman
    - foreman-proxy
