---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: httpd
  namespace: "{{ project_name }}"
  labels:
    app: httpd
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      serviceAccount: anyuid
      serviceAccountName: anyuid
      volumes:
        - name: httpd-config
          configMap:
            name: "httpd-configs"
        - name: certs
          secret:
            secretName: certs
            items:
              - path: katello-default-ca.crt
                key: ca.crt
              - path: server.crt
                key: server.crt
        - name: keys
          secret:
            secretName: keys
            items:
              - path: server.key
                key: server.key
      containers:
        - name: httpd
          image: "manageiq/httpd:latest"
          command:
            - /usr/sbin/init
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: httpd-config
              mountPath: "/etc/httpd/conf.d"
            - readOnly: true
              mountPath: /etc/pki/katello/private
              name: keys
            - readOnly: true
              mountPath: /etc/pki/katello/certs
              name: certs
          lifecycle:
            postStart:
              _exec:
                command:
                  - "/usr/bin/save-container-environment"
