---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: memcached
  namespace: "{{ project_name }}"
  labels:
    app: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          securityContext: {}
          image: manageiq/memcached
