---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: candlepin
  namespace: "{{ project_name }}"
  labels:
    app: candlepin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candlepin
  template:
    metadata:
      labels:
        app: candlepin
    spec:
      serviceAccount: anyuid
      serviceAccountName: anyuid
      containers:
        - name: candlepin
          securityContext: {}
          volumeMounts:
            - readOnly: true
              mountPath: /etc/candlepin/certs
              name: ca
          env:
            - name: POSTGRES_DB
              value: foreman
            - name: POSTGRES_USER
              value: foreman
            - name: POSTGRES_PASSWORD
              value: foreman
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_SERVICE
              value: postgres
            - name: QPID_SERVICE
              value: qpid
            - name: QPID_PORT
              value: '5672'
          image: "{{ registry }}/candlepin:latest"
      volumes:
        - secret:
            items:
              - path: candlepin-ca.key
                key: ca.key
              - path: candlepin-ca.crt
                key: ca.crt
            secretName: ca
          name: ca
