---
- name: get forklift versions
  forklift_versions:
    file: "{{ forklift_versions_file }}"
    scenario: "{{ scenario }}"
    scenario_version: "{{ scenario_version }}"
    scenario_os: "{{ scenario_os }}"
    scenario_version_offset: "{{ scenario_version_offset | default(omit) }}"
  register: forklift_versions
  delegate_to: localhost
  become: no

- name: set individual component vars
  set_fact: "{{ item.key }}={{ item.value }}"
  with_items: "{{ forklift_versions.versions | dict2items }}"
