---
- hosts: pipeline-proxy-3.3-centos7
  become: yes
  vars:
    puppet_repositories_version: 3
    foreman_proxy_content_server: pipeline-katello-3.3-centos7
    katello_version: 3.1
    foreman_version: 1.12
    foreman_repositories_use_koji: true
    katello_repositories_use_koji: true
    foreman_installer_scenario: capsule
    foreman_installer_options_internal_use_only:
      - '--foreman-proxy-trusted-hosts "{{ server_fqdn.stdout }}"
        --foreman-proxy-trusted-hosts "{{ ansible_nodename }}"
        --foreman-proxy-foreman-base-url "https://{{ server_fqdn.stdout }}"
        --foreman-proxy-register-in-foreman true
        --foreman-proxy-oauth-consumer-key "{{ oauth_consumer_key.stdout }}"
        --foreman-proxy-oauth-consumer-secret "{{ oauth_consumer_secret.stdout }}"
        --capsule-certs-tar "{{ foreman_proxy_content_certs_tar }}"
        --capsule-parent-fqdn "{{ server_fqdn.stdout }}"
        --capsule-pulp-oauth-secret "{{ pulp_oauth_secret.stdout }}"'
    foreman_installer_additional_packages:
      - foreman-installer-katello
  roles:
    - selinux
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - foreman_proxy_content
    - foreman_installer
