---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: foreman-proxy
  namespace: "{{ project_name }}"
  labels:
    app: foreman-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foreman-proxy
  template:
    metadata:
      labels:
        app: foreman-proxy
    spec:
      containers:
        - name: foreman-proxy
          securityContext: {}
          image: "{{ registry }}/foreman-proxy:latest"
