---
- name: "Build hosts file"
  include_tasks: "./hosts_file_record.yml"
  vars:
    ip: "{{ hostvars[item].ansible_host }}"
    domain: "{{ etc_hosts_domain }}"
    hostname: "{{ item }}"
  when: hostvars[item].ansible_host is defined
  become: yes
  with_items: "{{ groups['all'] }}"
  tags:
    - env_setup
