---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qpid
  namespace: "{{ project_name }}"
  labels:
    app: qpid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qpid
  template:
    metadata:
      labels:
        app: qpid
    spec:
      containers:
        - name: qpid
          securityContext: {}
          image: "{{ registry }}/qpid:latest"
      serviceAccount: anyuid
      serviceAccountName: anyuid
