---
- name: Create Foreman Proxy service
  k8s_raw:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml') | from_yaml }}"
  with_items:
    - foreman-proxy

- name: Create Foreman Proxy deployment
  k8s_raw:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml') | from_yaml }}"
  with_items:
    - foreman-proxy

- name: Create Foreman Proxy jobs
  k8s_raw:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.job.yaml') | from_yaml }}"
  with_items:
    - register
