- hosts: localhost
  vars:
    forklift_name: pipeline-smartproxy-powerdns
    forklift_boxes:
      pipeline-smartproxy-powerdns:
        box: centos7
        memory: 1024
  roles:
    - forklift

- hosts: pipeline-smartproxy-powerdns
  become: yes
  vars:
    bats_forklift_dir: /vagrant
    bats_update_forklift: "no"
    bats_tests:
      - "fb-proxy-dns.bats"
    foreman_installer_scenarios_answers:
      foreman: false
      foreman::cli: false
      foreman::plugin::setup: false
      foreman_proxy:
        register_in_foreman: false
        dns: true
        dns_managed: false
        dns_provider: powerdns
      foreman_proxy::plugin::dns::powerdns:
        backend: mysql
        manage_database: true
        mysql_password: ajooy7HeeCh8loo
        pdnssec: pdnsutil
    powerdns_db_pass: "ajooy7HeeCh8loo"
    powerdns_conf_mode: "0644"
    powerdns_zones:
      - "example.com"
      - "121.168.192.in-addr.arpa"
      - "8.b.d.0.1.0.0.2.ip6.arpa"
  roles:
    - selinux
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - disable_firewall
    - haveged
    - update_os_packages
    - foreman_installer
    - powerdns
    - bats
