- hosts: localhost
  vars:
    forklift_name: pipeline-katello-nightly-split
    forklift_boxes:
      pipeline-app-nightly-centos7-split:
        box: centos7
        memory: 4096
        ansible:
          group: "{{ forklift_name }}"
      pipeline-services-nightly-centos7-split:
        box: centos7
        memory: 4096
        ansible:
          group: "{{ forklift_name }}"
      pipeline-proxy-nightly-centos7-split:
        box: centos7
        memory: 3072
        ansible:
          group: "{{ forklift_name }}"
  roles:
    - forklift

- hosts:
  - pipeline-app-nightly-centos7-split
  - pipeline-proxy-nightly-centos7-split
  - pipeline-services-nightly-centos7-split
  become: yes
  vars:
    foreman_repositories_version: nightly
    foreman_repositories_environment: staging
    katello_repositories_version: nightly
    katello_repositories_environment: staging
    foreman_installer_skip_installer: true
    foreman_installer_additional_packages:
      - foreman-installer-katello
    foreman_installer_module_prs: 'katello/katello/209,katello/foreman_proxy_content/136'
  roles:
    - selinux
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - disable_firewall
    - haveged
    - update_os_packages
    - foreman_installer

- hosts: pipeline-services-nightly-centos7-split
  become: yes
  vars:
    foreman_installer_scenario: katello
    foreman_installer_options_internal_use_only:
      - "--disable-system-checks"
      - "--no-enable-foreman"
      - "--no-enable-foreman-cli"
      - "--no-enable-foreman-plugin-tasks"
      - "--no-enable-foreman-proxy"
      - "--no-enable-foreman-proxy-content"
      - "--no-enable-foreman-proxy-plugin-pulp"
      - "--no-enable-puppet"
      - "--katello-manage-application false"
      - "--katello-manage-pulp true"
      - "--katello-manage-candlepin true"
      - "--katello-manage-qpid true"
      - "--certs-group root"
  roles:
    - foreman_installer

- hosts: pipeline-app-nightly-centos7-split
  become: yes
  vars:
    foreman_installer_scenario: katello
    foreman_installer_options_internal_use_only:
      - "--disable-system-checks"
      - "--certs-generate false"
      - "--katello-manage-application true"
      - "--katello-manage-candlepin false"
      - "--katello-candlepin-hostname pipeline-services-nightly-centos7-split.{{ ansible_domain }}"
      - "--katello-manage-qpid false"
      - "--katello-qpid-hostname pipeline-services-nightly-centos7-split.{{ ansible_domain }}"
      - "--katello-manage-pulp false"
      - "--katello-pulp-hostname pipeline-services-nightly-centos7-split.{{ ansible_domain }}"
      # Don't install the meta package
      - "--katello-package-names tfm-rubygem-katello"
      - "--foreman-admin-password {{ foreman_installer_admin_password }}"
  roles:
    - foreman_installer

- hosts: pipeline-proxy-nightly-centos7-split
  become: yes
  vars:
    foreman_proxy_content_server: pipeline-app-nightly-centos7-split
    foreman_installer_scenario: foreman-proxy-content
    foreman_installer_options_internal_use_only:
      - '--disable-system-checks'
      - '--foreman-proxy-trusted-hosts "{{ server_fqdn.stdout }}"'
      - '--foreman-proxy-trusted-hosts "{{ ansible_nodename }}"'
      - '--foreman-proxy-foreman-base-url "https://{{ server_fqdn.stdout }}"'
      - '--foreman-proxy-register-in-foreman true'
      - '--foreman-proxy-oauth-consumer-key "{{ oauth_consumer_key.stdout }}"'
      - '--foreman-proxy-oauth-consumer-secret "{{ oauth_consumer_secret.stdout }}"'
      - '--foreman-proxy-content-certs-tar "{{ foreman_proxy_content_certs_tar }}"'
      - '--foreman-proxy-content-parent-fqdn "{{ server_fqdn.stdout }}"'
  roles:
    - foreman_proxy_content
    - foreman_installer

- hosts: pipeline-app-nightly-centos7-split
  become: true
  vars:
    bats_tests:
      - fb-test-katello.bats
      - fb-content-katello.bats
      - fb-proxy.bats
      - fb-destroy-organization.bats
      - fb-finish-katello.bats
  roles:
    - bats
