---
- name: 'Setup Puppet 3 Repository'
  yum:
    name: https://release-archives.puppet.com/yum/puppetlabs-release-el-{{ ansible_distribution_major_version }}.noarch.rpm
    disable_gpg_check: True
    state: present
  tags:
    - packages
