---
- name: 'Create Foreman application'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  shell: >
    oc process -f {{ role_path }}/files/foreman-template.yaml
    ENABLE_KATELLO={{ foreman_enable_katello }}
    DATABASE_USER={{ foreman_database_user }}
    DATABASE_NAME={{ foreman_database }}
    DATABASE_PASSWORD={{ foreman_database_password }}
    | oc create -f -
