---
- name: 'Get Server Hostname'
  shell: hostname -f
  delegate_to: "{{ foreman_proxy_content_server }}"
  register: server_fqdn

- name: 'Query Foreman server'
  uri:
    url: "{{ 'https://' ~ server_fqdn.stdout }}"
  ignore_errors: True
  register: foreman_get

- name: 'Check for rails server'
  fail: msg="No rails server detected running on {{ foreman_proxy_content_server }}"
  when: foreman_get.status != 200

- name: 'Add group foreman'
  group: name=foreman state=present
  delegate_to: "{{ foreman_proxy_content_server }}"
