---
- name: 'Gather facts from {{ foreman_proxy_content_server }}'
  setup:
  delegate_to: "{{ foreman_proxy_content_server }}"
  delegate_facts: true

- name: 'Get Server Hostname'
  set_fact:
    server_fqdn: "{{ hostvars[foreman_proxy_content_server].ansible_nodename }}"

- name: 'Get oauth-consumer-key'
  shell: grep oauth_consumer_key "{{ foreman_directory }}"settings.yaml | cut -d ' ' -f 2
  delegate_to: "{{ foreman_proxy_content_server }}"
  register: oauth_consumer_key

- name: 'Get oauth-consumer-secret'
  shell: grep oauth_consumer_secret "{{ foreman_directory }}"settings.yaml | cut -d ' ' -f 2
  delegate_to: "{{ foreman_proxy_content_server }}"
  register: oauth_consumer_secret

- include_tasks: certs_generate.yml

- name: 'Change cert permissions'
  file: path='/etc/pki/katello/private' mode=0775
  delegate_to: "{{ foreman_proxy_content_server }}"
  when: devel is defined and devel == true

- name: 'Install Capsule Installer RPM'
  yum:
    name: foreman-proxy-content
  when: custom_install == False
