---
- include_tasks: certs_generate.yml

- name: 'Run installer upgrade'
  include_role:
    name: foreman_installer
  vars:
    foreman_installer_scenario: foreman-proxy-content
    foreman_installer_upgrade: True
    foreman_installer_options_internal_use_only:
      - --certs-regenerate=true
      - --certs-deploy=true
      - --certs-tar-file="{{ foreman_proxy_content_certs_tar }}"
