---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "pulp"
  annotations:
    description: "Pulp application"
    tags: "quickstart,pulp"
labels:
  template: "pulp"
objects:
  - kind: "ImageStream"
    apiVersion: "v1"
    metadata: 
      name: "${NAME}-base"
      annotations: 
        description: "Keeps track of changes in the application image"

  - kind: "ImageStream"
    apiVersion: "v1"
    metadata: 
      name: "${NAME}-apache"
      annotations: 
        description: "Keeps track of changes in the application image"

  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      name: "${NAME}-base"
    spec: 
      source: 
        type: "Git"
        git:
          uri: "https://github.com/ehelms/foreman-docker-compose.git"
          ref: "compose-to-openshift"
        contextDir: "pulp/base"
      strategy:
        type: "Docker"
        dockerStrategy:
          dockerfilePath: Dockerfile
      triggers: 
        - type: "ImageChange"
        - type: "ConfigChange"
      output:
        to:
          kind: "ImageStreamTag"
          name: "${NAME}-base:latest"

  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      name: "${NAME}-apache"
    spec: 
      source: 
        type: "Git"
        git:
          uri: "https://github.com/ehelms/foreman-docker-compose.git"
          ref: "compose-to-openshift"
        contextDir: "pulp/apache"
      strategy:
        type: "Docker"
        dockerStrategy:
          dockerfilePath: Dockerfile
          from:
            kind: "ImageStreamTag"
            name: "pulp-base:latest"
      triggers: 
        - type: "ImageChange"
        - type: "ConfigChange"
      output:
        to:
          kind: "ImageStreamTag"
          name: "${NAME}-apache:latest"

  - kind: "Service"
    apiVersion: "v1"
    metadata: 
      name: "${NAME}"
      annotations: 
        description: "Exposes and load balances the application pods"
    spec: 
      ports: 
        - name: "web"
          port: 8080
          targetPort: 8080
      selector: 
        name: "${NAME}"

  - kind: "Route"
    apiVersion: "v1"
    metadata: 
      name: "${NAME}"
    spec: 
      host: ""
      to: 
        kind: "Service"
        name: "${NAME}"

  - kind: "DeploymentConfig"
    apiVersion: "v1"
    metadata:
      name: "${NAME}"
      annotations:
        description: "Defines how to deploy the application server"
    spec:
      strategy:
        type: "Recreate"
        recreateParams:
          pre:
            failurePolicy: "Abort"
            execNewPod:
              containerName: "${NAME}-apache"
              command:
                - pulp-manage-db
              volumes:
                - dev-log
      triggers:
        - type: "ImageChange"
          imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}-apache"
            from:
              kind: "ImageStreamTag"
              name: "${NAME}-apache:latest"
        - type: "ConfigChange"
      selector:
        name: "${NAME}"
      replicas: 1
      template:
        metadata:
          name: "${NAME}"
          labels:
            name: "${NAME}"
        spec:
          restartPolicy: Always
          containers:
            - name: "pulp-apache"
              image: "${NAME}-apache:latest"
              ports:
                - containerPort: 8080
                  protocol: TCP
              args:
                - httpd
                - "-D"
                - FOREGROUND
              resources: {}
              env: []
              volumeMounts:
                - name: dev-log
                  mountPath: /dev/log
          volumes:
            - name: dev-log
              emptyDir:
                path: /dev/log

parameters: 
  - name: "NAME"
    displayName: "Name"
    description: "The name assigned to all of the frontend objects defined in this template."
    required: true
    value: "pulp"

  - name: "NAMESPACE"
    displayName: "Namespace"
    required: true
    description: "The OpenShift Namespace where the ImageStream resides."
    value: "openshift"

  - name: "CONTEXT_DIR"
    displayName: "Context Directory"
    description: "Set this to the relative path to your project if it is not in the root of your repository."

  - name: "APPLICATION_USER"
    displayName: "Application Username"
    required: true
    description: "The application user that is used within the sample application to authorize access on pages."
    value: "admin"

  - name: "APPLICATION_PASSWORD"
    displayName: "Application Password"
    required: true
    description: "The application password that is used within the sample application to authorize access on pages."
    value: "changeme"

  - name: "DATABASE_SERVICE_NAME"
    required: true
    displayName: "Database Service Name"
    value: "mongodb"

  - name: "DATABASE_USER"
    displayName: "Database Username"
    generate: "expression"
    from: "user[A-Z0-9]{3}"

  - name: "DATABASE_PASSWORD"
    displayName: "Database Password"
    generate: "expression"
    from: "[a-zA-Z0-9]{8}"

  - name: "DATABASE_NAME"
    required: true
    displayName: "Database Name"
    value: "root"

  - name: "MEMORY_LIMIT"
    displayName: "Memory Limit"
    required: true
    description: "Maximum amount of memory the Rails container can use."
    value: "512Mi"
