---
- hosts: localhost
  vars:
    postgresql_user: candlepin
    postgresql_password: candlepin
    postgresql_database: candlepin
    postgresql_port: 5432
    postgresql_host: postgresql
  tasks:
    - name: 'Create .tmp directory'
      file:
        path: .tmp

    - name: 'Clone templates repository'
      git:
        repo: https://github.com/openshift/openshift-ansible.git
        dest: .tmp/openshift-ansible

    - name: 'Create Candlepin project'
      command: oc new-project candlepin --description="Candlepin on Openshift" --display-name="Candlepin"

    - name: 'Load default imagestreams'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/image-streams/image-streams-centos7.json

    - name: 'Load database templates'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/db-templates

    - name: 'Load quickstart templates'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/quickstart-templates

    - name: 'Create Postgres application'
      command: >
        oc new-app postgresql-ephemeral
        -p POSTGRESQL_USER={{ postgresql_user }}
        -p POSTGRESQL_PASSWORD={{ postgresql_password }}
        -p POSTGRESQL_DATABASE={{ postgresql_database }}
    
    - name: 'Create Candlepin template'
      command: oc create -f templates/candlepin.yaml

    - name: 'Create Candlepin application'
      command: >
        oc new-app candlepin
        -p DATABASE_USER={{ postgresql_user }}
        -p DATABASE_PASSWORD={{ postgresql_password }}
        -p DATABASE_NAME={{ postgresql_database }}
