---
- hosts: pipeline-katello-3.3-centos7
  become: yes
  vars_files:
    - vars.yml
  vars:
    foreman_installer_scenario: katello
    foreman_installer_options_internal_use_only:
      - "--disable-system-checks"
      - "--foreman-admin-password {{ foreman_installer_admin_password }}"
    foreman_installer_additional_packages:
      - katello
  roles:
    - selinux
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - foreman_installer
