---
- hosts: localhost
  tasks:
    - name: 'Create .tmp directory'
      file:
        path: .tmp

    - name: 'Clone templates repository'
      git:
        repo: https://github.com/openshift/openshift-ansible.git
        dest: .tmp/openshift-ansible

    - name: 'Create Foreman Proxy project'
      command: oc new-project foreman-proxy --description="Foreman Proxy" --display-name="The Foreman Proxy"

    - name: 'Load default imagestreams'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/image-streams/image-streams-centos7.json

    - name: 'Load database templates'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/db-templates

    - name: 'Load quickstart templates'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/quickstart-templates
    
    - name: 'Create Puppetserver template'
      command: oc create -f templates/puppet.yaml

    - name: 'Create Puppetserver application'
      command: >
        oc new-app puppet
    - name: 'Create Foreman Proxy template'
      command: oc create -f templates/foreman-proxy.yaml

    - name: 'Create Foreman Proxy application'
      command: >
        oc new-app foreman-proxy
