---
- hosts: localhost
  vars:
    postgresql_user: foreman
    postgresql_password: foreman
    postgresql_database: foreman
    postgresql_port: 5432
    postgresql_host: postgresql
    mongodb_user:  admin
    mongodb_password: admin
    mongodb_database: pulp_database
  tasks:
    - name: 'Create .tmp directory'
      file:
        path: .tmp

    - name: 'Clone templates repository'
      git:
        repo: https://github.com/openshift/openshift-ansible.git
        dest: .tmp/openshift-ansible

    - name: 'Create Foreman project'
      command: oc new-project foreman-katello --description="Foreman with Katello on Openshift" --display-name="The Foreman with Katello"

    - name: 'Load default imagestreams'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/image-streams/image-streams-centos7.json

    - name: 'Load database templates'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/db-templates

    - name: 'Load quickstart templates'
      command: oc create -f .tmp/openshift-ansible/roles/openshift_examples/files/examples/v1.4/quickstart-templates

    - name: 'Create Postgres application'
      command: >
        oc new-app postgresql-ephemeral
        -p POSTGRESQL_USER={{ postgresql_user }}
        -p POSTGRESQL_PASSWORD={{ postgresql_password }}
        -p POSTGRESQL_DATABASE={{ postgresql_database }}

    - name: 'Create MongoDB application'
      command: >
        oc new-app mongodb-ephemeral
        -p MONGODB_USER={{ mongodb_user }}
        -p MONGODB_ADMIN_PASSWORD={{ mongodb_password }}
        -p MONGODB_PASSWORD={{ mongodb_password }}
        -p MONGODB_DATABASE={{ mongodb_database }}
    
    - name: 'Create Candlepin template'
      command: oc create -f templates/candlepin.yaml

    - name: 'Create Candlepin application'
      command: >
        oc new-app candlepin
        -p DATABASE_USER={{ postgresql_user }}
        -p DATABASE_PASSWORD={{ postgresql_password }}
        -p DATABASE_NAME={{ postgresql_database }}
    
    - name: 'Create Qpid template'
      command: oc create -f templates/qpid.yaml

    - name: 'Create Qpid application'
      command: >
        oc new-app qpid
    
    - name: 'Create Pulp template'
      command: oc create -f templates/pulp.yaml

    - name: 'Create Pulp application'
      command: >
        oc new-app pulp
        -p DATABASE_USER={{ mongodb_user }}
        -p DATABASE_PASSWORD={{ mongodb_password }}
        -p DATABASE_NAME={{ mongodb_database }}
    
    - name: 'Create Foreman template'
      command: oc create -f templates/foreman.yaml

    - name: 'Create Foreman application'
      command: >
        oc new-app foreman
        -p ENABLE_KATELLO="true"
        -p DATABASE_USER={{ postgresql_user }}
        -p DATABASE_NAME={{ postgresql_database }}
        -p DATABASE_PASSWORD={{ postgresql_password }}
    
    - name: 'Create Foreman Proxy template'
      command: oc create -f templates/foreman-proxy.yaml

    - name: 'Create Foreman Proxy application'
      command: >
        oc new-app foreman-proxy
    
    - name: 'Create Puppetserver template'
      command: oc create -f templates/puppet.yaml

    - name: 'Create Puppetserver application'
      command: >
        oc new-app puppet

    - name: 'Create Persisten Volume Claim'
      command: oc create -f claims/pulp_content.yaml
