- hosts: all
  become: true
  vars:
    katello_repositories_version: nightly
    katello_repositories_use_koji: true
    puppet_repositories_version: 4
    foreman_installer_scenario: katello
    foreman_installer_pkg: katello
    foreman_installer_options:
      - "--disable-system-checks"
      - "--skip-checks-i-know-better"
    foreman_installer_scenarios_answers:
      foreman:
        admin_password: changeme
      katello:
        enable_ostree: true
    bats_tests:
      - "fb-test-foreman.bats"
      - "fb-test-katello.bats"
      - "fb-content-katello.bats"
      - "fb-destroy-organization.bats"
      - "fb-finish.bats"
  roles:
    - selinux
    - etc_hosts
    - disable_ipv6
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - disable_firewall
    - haveged
    - swapfile
    - foreman_installer
    - bats
