---
- hosts: devel
  become: true
  vars:
    katello_repositories_version: nightly
    foreman_installer_scenario: katello-devel
    foreman_installer_pkg: foreman-installer-katello-devel
    foreman_installer_options:
      - "--disable-system-checks"
    foreman_installer_scenarios_answers:
      katello_devel:
        github_username: "{{ katello_devel_github_username }}"
        enable_ostree: true
  roles:
    - etc_hosts
    - epel_repositories
    - ostree_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - foreman_devel
    - foreman_installer
