- hosts: all
  become: true
  roles:
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - role: foreman_installer
      scenario: katello
      foreman_installer_options:
        - "--disable-system-checks"
      foreman_installer_scenarios_answers:
        foreman:
          admin_password: changeme
        foreman::plugin::discovery: true
        foreman::plugin::bootdisk: true
        foreman::plugin::remote_execution: true
        foreman::plugin::hooks: true
        foreman::plugin::openscap: true
        foreman_proxy::plugin::openscap: true
        foreman_proxy::plugin::remote_execution::ssh: true
      foreman_installer_pkg: katello
