---
- hosts: server foreman-proxy-content
  become: true
  vars:
    foreman_proxy_content_server_group: "server-{{ inventory_hostname }}"
    foreman_proxy_content_server: "{{ groups[foreman_proxy_content_server_group][0] }}"
    katello_repositories_version: nightly
  roles:
    - foreman_repositories
    - katello_repositories
    - puppet_repositories
    - epel_repositories
    - ostree_repositories
    - etc_hosts
    - {role: foreman_proxy_content, foreman_directory: '/home/vagrant/foreman/config/',
       devel: True, base_foreman_directory: '/home/vagrant/foreman/'}
    - role: foreman_installer
      foreman_installer_scenario: foreman-proxy-content
      foreman_installer_options:
        - '--disable-system-checks'
      foreman_installer_scenarios_answers:
        foreman_proxy_content:
          certs_tar: "{{ foreman_proxy_content_certs_tar }}"
          parent_fqdn: "{{ server_fqdn.stdout }}"
          pulp_oauth_secret: "{{ pulp_oauth_secret.stdout }}"
          enable_ostree: true
        foreman_proxy:
          oauth_consumer_key: "{{ oauth_consumer_key.stdout }}"
          oauth_consumer_secret: "{{ oauth_consumer_secret.stdout }}"
          foreman_base_url: "https://{{ server_fqdn.stdout }}"
          trusted_hosts:
            - "{{ server_fqdn.stdout }}"
            - "{{ ansible_nodename }}"
