- hosts: all
  become: true
  roles:
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - role: foreman_installer
      scenario: katello
      foreman_installer_options_internal_use_only: "--disable-system-checks"
      foreman_installer_additional_packages:
          - katello
