---
- hosts: all
  become: true
  roles:
    - role: etc_hosts
    - role: foreman_server_repositories
      foreman_server_repositories_ostree: true
      foreman_server_repositories_katello: true
      foreman_server_repositories_foreman_client: true
    - role: ruby_scl
    - role: foreman_installer_devel_scenario
    - role: foreman_installer
      katello_repositories_version: nightly
      foreman_installer_scenario: katello-devel
      katello_devel_github_username: ''
      foreman_installer_options_internal_use_only:
        - "--disable-system-checks"
        - "--katello-devel-github-username '{{ katello_devel_github_username }}'"
        - "--katello-devel-enable-ostree=true"
        - "--katello-devel-extra-plugins theforeman/foreman_remote_execution"
        - "--katello-devel-extra-plugins theforeman/foreman_discovery"
        - "--katello-devel-extra-plugins theforeman/foreman_ansible"
        - "--katello-devel-extra-plugins theforeman/foreman-tasks"
        - "--katello-devel-extra-plugins theforeman/foreman_bootdisk"
        - "--katello-devel-extra-plugins theforeman/foreman_openscap"
        - "--katello-devel-extra-plugins theforeman/foreman_templates"
        - "--katello-devel-extra-plugins theforeman/foreman_hooks"
      foreman_installer_additional_packages:
        - foreman-installer-katello
