---
- hosts: openshift
  become: true
  roles:
    - etc_hosts

- hosts: openshift
  become: true
  vars:
    openshift_version: "v1.4.0-rc1+b4e0954"
  tasks:
    - name: 'Update system'
      yum:
        name: "*"
        state: latest

    - name: 'Download openshift release'
      unarchive:
        #src: "https://github.com/openshift/origin/releases/download/v1.4.0-rc1/openshift-origin-server-{{ openshift_version }}-linux-64bit.tar.gz"
        src: https://github.com/openshift/origin/releases/download/v1.4.0-rc1/openshift-origin-server-v1.4.0-rc1.b4e0954-linux-64bit.tar.gz
        dest: /root
        creates: /root/openshift-origin-server-v1.4.0-rc1.b4e0954-linux-64bit
        remote_src: yes

    - name: 'Download openshift release'
      unarchive:
        src: https://github.com/openshift/origin/releases/download/v1.4.0-rc1/openshift-origin-client-tools-v1.4.0-rc1.b4e0954-linux-64bit.tar.gz
        dest: /root
        creates: /root/openshift-origin-client-tools-v1.4.0-rc1.b4e0954-linux-64bit
        remote_src: yes

    - name: 'Set CLI on PATH'
      file:
        state: link
        src: "/root/openshift-origin-client-tools-{{ openshift_version }}-linux-64bit/oc"
        dest: "/usr/sbin/oc"

    - name: 'Start openshift'
      shell: nohup ./openshift start &
      args:
        chdir: "/root/openshift-origin-server-{{ openshift_version }}-linux-64bit"

    - name: 'Clone templates repository'
      git:
        repo: https://github.com/openshift/openshift-ansible.git
        dest: /root/openshift-ansible

    - name: 'Login to openshift'
      command: oc login {{ ansible_hostname }}:8443 -u admin -p admin --insecure-skip-tls-verify=true

    - name: 'Load default imagestreams'
      command: oc create -f /root/openshift-ansible/roles/openshift_examples/files/examples/v1.4/image-streams/image-streams-centos7.json

    - name: 'Load database templates'
      command: oc create -f /root/openshift-ansible/roles/openshift_examples/files/examples/v1.4/db-templates

    - name: 'Load quickstart templates'
      command: oc create -f /root/openshift-ansible/roles/openshift_examples/files/examples/v1.4/quickstart-templates
