---
- hosts: all
  become: true
  vars:
    vagrant_libvirt: true
    vagrant_version: 2.1.1
  roles:
    - role: libvirt
    - role: vagrant
    - role: epel_repositories

- hosts: all
  become: true
  vars:
    forklift_url: "https://github.com/theforeman/forklift"
    forklift_version: master
  tasks:
    - name: 'Disable mirror.ci.centos.org'
      ini_file:
        path: /etc/yum/pluginconf.d/fastestmirror.conf
        section: main
        option: exclude
        value: mirror.ci.centos.org

    - name: 'Install Forklift dependencies'
      package:
        name:
          - ansible
          - git
          - rubygem-deep_merge
        state: 'present'

    - name: 'Clone Forklift'
      git:
        repo: "{{ forklift_url }}"
        version: "{{ forklift_version }}"
        dest: './forklift'
