---
- hosts: all
  become: true
  vars:
    vagrant_libvirt: true
  roles:
    - role: libvirt
    - role: vagrant
    - role: epel_repositories

- hosts: all
  become: true
  vars:
    forklift_url: "https://github.com/theforeman/forklift"
    forklift_dest: "{{ ansible_env.HOME }}/forklift"
    forklift_version: master
    forklift_config:
      libvirt_options:
        volume_cache: unsafe
      boxes:
        exclude:
          - '^[^p]'
  tasks:
    - name: 'Install Forklift dependencies'
      package:
        name:
          - ansible
          - git
          - rubygem-deep_merge
        state: 'present'

    - name: 'Clone Forklift'
      git:
        repo: "{{ forklift_url }}"
        version: "{{ forklift_version }}"
        dest: "{{ forklift_dest }}"

    - name: 'Configure Forklift'
      copy:
        content: "{{ forklift_config | to_json | from_json | to_nice_yaml }}"
        dest: "{{ forklift_dest }}/vagrant/settings.yaml"
