---
foreman_installer_additional_packages: []
foreman_installer_admin_password: changeme
foreman_installer_skip_installer: False
foreman_installer_verbose: True
foreman_installer_scenario: foreman

# Comma-separated list of "organization/module/pr_number", e.g. "katello/capsule/37,katello/certs/34"
foreman_installer_module_prs: ""

# There are two options strings, so a user can supply their own, and
# a playbook can specify theirs. For example, katello needs
# "--disable-system-checks" so we put it in internal_use_only.
foreman_installer_options: ""
foreman_installer_options_internal_use_only: ""
